// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/RangelReale/fproto-wrap-std/jsonobject.proto

/*
Package gwproto is a generated protocol buffer package.

It is generated from these files:
	github.com/RangelReale/fproto-wrap-std/jsonobject.proto
	github.com/RangelReale/fproto-wrap-std/jsontag.proto
	github.com/RangelReale/fproto-wrap-std/options.proto
	github.com/RangelReale/fproto-wrap-std/sqltag.proto
	github.com/RangelReale/fproto-wrap-std/time.proto
	github.com/RangelReale/fproto-wrap-std/uuid.proto

It has these top-level messages:
	JSONObject
	JSONTag
	FProtoWrapOptions
	SQLTag
	NullTime
	UUID
	NullUUID
*/
package gwproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type JSONObject struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *JSONObject) Reset()                    { *m = JSONObject{} }
func (m *JSONObject) String() string            { return proto.CompactTextString(m) }
func (*JSONObject) ProtoMessage()               {}
func (*JSONObject) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *JSONObject) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*JSONObject)(nil), "fproto_wrap.JSONObject")
}

func init() {
	proto.RegisterFile("github.com/RangelReale/fproto-wrap-std/jsonobject.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4f, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x0f, 0x4a, 0xcc, 0x4b, 0x4f, 0xcd, 0x09, 0x4a, 0x4d,
	0xcc, 0x49, 0xd5, 0x4f, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2d, 0x2f, 0x4a, 0x2c, 0xd0, 0x2d,
	0x2e, 0x49, 0xd1, 0xcf, 0x2a, 0xce, 0xcf, 0xcb, 0x4f, 0xca, 0x4a, 0x4d, 0x2e, 0xd1, 0x03, 0xcb,
	0x08, 0x71, 0x43, 0x54, 0xc4, 0x83, 0x54, 0x28, 0x29, 0x71, 0x71, 0x79, 0x05, 0xfb, 0xfb, 0xf9,
	0x83, 0x15, 0x08, 0x89, 0x70, 0xb1, 0x96, 0x25, 0xe6, 0x94, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x06, 0x41, 0x38, 0x4e, 0xe6, 0x51, 0xa6, 0x44, 0xda, 0x95, 0x9e, 0x0f, 0x62, 0xea, 0xa7,
	0x97, 0x83, 0xc5, 0x93, 0xd8, 0xc0, 0x94, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x22, 0x84, 0x15,
	0x4a, 0xab, 0x00, 0x00, 0x00,
}
